### ISSUE TITLE
Fabric8 Maven Plugin deprecation

### ISSUE THREAD

**Issue by manusa** [eclipse-jkube/jkube#287]
## Description
Main goal of Eclipse JKube is to replace [Fabric8 Maven Plugin](https://github.com/fabric8io/fabric8-maven-plugin).

## Tasks
- [x] Deprecation notice -> Link to Eclipse JKube
- [x] Review all open [PRs](https://github.com/fabric8io/fabric8-maven-plugin/pulls)
- [x] Add final deprecation notice
- [x] Create an intermediate release (Update all Mojos to at least print a final `WARNING` message with deprecation and link to Eclipse JKube)
  - #1426 
  - https://github.com/fabric8io/fabric8-maven-plugin/releases/tag/v4.4.2
- [x] Archive Repository
- [ ] Create a final release (x.x.x) that won't execute any goal unless a flag to ignore the project deprecation is provided (2023-01-21)
- [ ] ~_Create final release (5.0.0) that automatically migrates users to JKube._~
- [ ] Provide solution to https://bugzilla.redhat.com/show_bug.cgi?id=1827201 by pointing to JKube release

Deprecation should be effective after a few months of notice announce.

**Comment by sunix** [comment]
Maybe what we can do is in the next release:
- fail when excuting one of the goals.
- display warnings about the problems with using fmp and provide different resolution options
- have a flag for user who still wants to use fmp that would reenable the goals.

**Comment by manusa** [comment]
Any additional work regarding the Fabric8 Maven Plugin should be addressed in separate issues.
The project is now archived and its clear that it's no longer maintained.
