### ISSUE TITLE
[EPIC] Buildpacks-based container image build strategy

### ISSUE THREAD

**Issue by manusa** [eclipse-jkube/jkube#439]
### Description

As a user, I want to be able to use Eclipse JKube to build container images and deploy them to a Kubernets-compatible cluster for my Java application leveraging Buildpacks, so that I can take advantage and reuse one of the many production ready [buildpacks](https://registry.buildpacks.io/) to create an image for my application.

Buildpacks is used by many frameworks, such as Spring Boot, to create container images for an application. There is a curated, community-maintained, growing list of buildpacks to support all kinds of frameworks, libraries, and programming languages.

Currently, [JKube can be made compatible](https://www.callibrity.com/blog/spring-into-kubernetes) with Buildpacks-produced container images by tuning the image name at the buildpacks level, or modifying JKube's resource configuration.
However, this is cumbersome and requires the user to provide additional configurations.

It would be good to have a transparent, seamless integration with Buildpacks (similar to what we have for Jib). This way, a user wouldn't need to worry about additional configurations and could simply leverage Buildpacks by configuring it as JKube's [container image build strategy](https://eclipse.dev/jkube/docs/kubernetes-maven-plugin/#build-goal-configuration).

### Tasks
- [x] Spike a PoC implementation to see if this is possible
- [x] Draft a design document
  https://docs.google.com/document/d/1HYSEad6pLBvtHJqyCmNdUUTE3lhIdCDd1AtmA5p-9MY/
- [x] Create individual development tasks and stories
  - https://github.com/eclipse/jkube/issues/2465
    - https://github.com/eclipse/jkube/issues/2453
    - https://github.com/eclipse/jkube/issues/2454
      - https://github.com/eclipse/jkube/issues/2456
    - #2493
    - #2491
    - #2492 
    - #2464
  - https://github.com/eclipse/jkube/issues/2470
  - https://github.com/eclipse/jkube/issues/2459
  - https://github.com/eclipse/jkube/issues/2466
  - #2494
    - https://github.com/eclipse/jkube/issues/2461
    - https://github.com/eclipse/jkube/issues/2462
  - https://github.com/eclipse-jkube/jkube/issues/3097 
  
To be discussed later:
  - https://github.com/eclipse/jkube/issues/2460

  - https://github.com/eclipse/jkube/issues/2463

### See also:
- https://buildpacks.io/
- https://github.com/paketo-buildpacks
- https://github.com/spring-projects/spring-boot/tree/3657c6c85de0bd49529d2dc256dd4350b61ad7c1/spring-boot-project/spring-boot-tools/spring-boot-buildpack-platform/src/main/java/org/springframework/boot/buildpack/platform

### Relates to:
- #66

**Comment by manusa** [comment]
https://github.com/snowdrop/java-buildpack-client

**Comment by gbraad** [comment]
### Related

https://github.com/eclipse/jkube/pull/2338

**Comment by rohanKanojia** [comment]
Shall we close this one? The only open issue should be closed by https://github.com/eclipse-jkube/jkube-integration-tests/pull/371
